### ISSUE TITLE
补全如果使用ycm就更好了

### ISSUE THREAD

**Issue by M-Kepler** [tao12345666333/vim#10]
还没试这个vimrc，用自己的习惯了

**Comment by tao12345666333** [comment]
我用过。 但是使用YCM会让我的Vim变慢， 使用工具嘛，用着爽和效率都是很重要的衡量标准， 所以我还是放弃了YCM。 况且要写的语言种类会多一些， YCM和Neo在这种情况下比较，没有特别的优势让我选择它。 此外还有一个原因，因为要更高效的在很多机器上获得（和自己机器）相同的体验， 快速的完成安装配置也是一个标准， 很明显使用YCM会花费比此更多的时间~
