### ISSUE TITLE
问问：有没window下的来一份呗

### ISSUE THREAD

**Issue by seekwe** [tao12345666333/vim#12]
rmbp丢一边好久没用了

**Comment by tao12345666333** [comment]
@seekwe  这份配置可直接在windows上使用.  之前有人发邮件问过我了, 他也在windows直接使用了这份配置了.  

另外记得设置 `behave mswin` 可以参考 https://github.com/tao12345666333/VimforWindowssetting/blob/master/_vimrc 里面的部分配置.
