### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [tao12345666333/vim#14]
![selection_002](https://cloud.githubusercontent.com/assets/6966410/21890595/5e125bbe-d909-11e6-9f20-e81414141384.png)

OS：Elementary OS 0.4.1

是不是缺少字体？如何排查这个问题？

**Comment by tao12345666333** [comment]
这是 `airline` 字体显示的问题.  你可以查看  https://github.com/tao12345666333/vim/issues/6 来进行解决.

* clone powerline fonts 仓库(https://github.com/powerline/fonts)
* 执行项目中的 install.sh 安装字体
* 修改终端配置中使用的字体为 xxx for Powerline即可。

**Comment by JamesLiAndroid** [comment]
解决了，谢谢！

**Comment by tao12345666333** [comment]
不客气~
