### ISSUE TITLE
补全后的问题

### ISSUE THREAD

**Issue by haodong** [tao12345666333/vim#15]
触发补全后会出现候选菜单，然而有时候并不需要候选菜单里的结果。
这时候继续输入 假如要空格或换行 那么又会自动填充默认候选内容
请问怎么解决这个问题？

**Comment by tao12345666333** [comment]
可以 `Ctrl + e` 来取消补全~

**Comment by haodong** [comment]
@tao12345666333 是的，发完这个issue后别人告诉我了，所以又close。
能否加在readme里让更多人知道？
谢谢！

**Comment by tao12345666333** [comment]
@haodong   readme 中是有的~  具体请看这个 https://github.com/tao12345666333/vim/blob/master/README-zh.md#支持操作-5  我专门写过的~

**Comment by tao12345666333** [comment]
好像发出来的链接锚点打开有点问题，在这里再贴一下好了


#### 支持操作

|      快捷键           |         解释               |
|-----------------------|:--------------------------:|
|      \<Tab>           | 使用Tab键进行待提示项目选择|
|      \<C-g>           |    取消补全                |
|      \<C-l>           | 完成待补全项中共同的字符串 |
|      \<C-h>           |     关闭待选项             |
|      \<C-y>           |     关闭待选项             |
|      \<C-e>           |     退出待选项             |
|      \<BS>            |     关闭待选项             |

**Comment by haodong** [comment]
谢谢你指出来。
之前我只看的是英文版readme，刚才看了英文版的也还是没有这个表。

**Comment by tao12345666333** [comment]
恩恩~  英文版的还没来得及补全 orz  我的锅~
