### ISSUE TITLE
hi, 

### ISSUE THREAD

**Issue by lfwin** [tao12345666333/vim#16]
I am a beginners for vim, how to use this ide to write , debug, run python, could you give a tutorial about writing little python code on this ide.
Many thanks

**Comment by tao12345666333** [comment]
If you've learned the basic usage of Vim, you can configure it use https://github.com/tao12345666333/vim/blob/master/README.md#install.

After install, you can follow the instructions below to do something.


```
vim new_file.py
```

The Vim will auto insert header.
```
#!/usr/bin/env python
# coding=utf-8
```

When you save, it will auto lint code syntax, and show message on bottom. Or you can  use  `\e` to show all error message. 

And you can run  `:PymodeRun` to run this file, use `:PymodeLintAuto` to auto lint.

**Comment by lfwin** [comment]
`:PymodeRun` works, but seems it can not add parameters for running a script, such python add.py 3 2.

**Comment by tao12345666333** [comment]
If you want to add some parameters to the script, you can use  `:!python add.py 3.2`

**Comment by lfwin** [comment]
I already try this, but console window will cover the code script window,  so not easy for me to debug without seeing the entire code block, or have to open another file to check, this is a little incovenient.

**Comment by tao12345666333** [comment]
@lfwin  If you use Vim 8, there have a way to run code async, and it can open a window to show the run status and results.

**Comment by lfwin** [comment]
thanks very much
