### ISSUE TITLE
怎么复制 vim里面的内容  ~~~~~搞不定

### ISSUE THREAD

**Issue by jonfoo86** [tao12345666333/vim#17]

**Comment by tao12345666333** [comment]
复制

如果是 对于同一 Vim 会话来说，  `yy`  复制 `p` 粘贴

对于想要访问系统粘贴板的话，按住 `shift` 键，然后依次按下  `'=y`  即可将所选内容复制到系统粘贴板，  同样按住 `shift` 键， 然后依次按下 `'=p` 即可将系统粘贴板内的内容粘贴至 vim 中.


记得要查看下 vim 的版本， 执行 `vim --version` 是否包含 `+clipboard` 这项 @jonfoo86

**Comment by jonfoo86** [comment]
搞定了， 可能和终端有关系， 我终端右键就会进入visual 模式， 不能用鼠标选择和复制东西, set mouse-=a  vimrc 里面加上这个就好了！ 

nice ， 你这个很棒,安装很方便， 

但是还是想提点建议， 能不能把 一些功能给介绍下， 
我好想没在里面发现自动格式化的功能

好像智能提示也不是很方便， 

听说快出c++ 的拉？  如果需要的话我可以提供一些很好使用的库， 我一直使用vim 进行c++ 开发大约6年了

**Comment by tao12345666333** [comment]
https://github.com/tao12345666333/vim/blob/master/README-zh.md   这里有主要的介绍~

我抽空再补充一下其他的~

欢迎一起补充哇~
