### ISSUE TITLE
how to set version warning???

### ISSUE THREAD

**Issue by chituma110** [tao12345666333/vim#22]
![image](https://user-images.githubusercontent.com/7559308/43496933-8b103b50-9572-11e8-859f-09cfa8092dc8.png)
I have get an problem about vim version. Can you tell me how to solve the problem?

**Comment by tao12345666333** [comment]
Now, you can try the docker image provides by me.

```
sudo docker run -it -v $PWD:/src --rm taobeier/vim
```

Or use the GitLab registry, where the image is automatically built weekly and all dependent packages are updated.

```
sudo docker run -it -v $PWD:/src --rm registry.gitlab.com/taobeier/vim
```
