### ISSUE TITLE
I have some problem about imp.

### ISSUE THREAD

**Issue by yifan2223** [tao12345666333/vim#23]
/must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favou
r of importlib; 
I find some answer at https://github.com/SirVer/ultisnips/issues/996
if has('python3')
  silent! python3 1
endif

but it can't work.
my vim is 8.1. Python is 8.1.0279. macOS 10.12.5

**Comment by tao12345666333** [comment]
Can you show me your `vim --version` ?

**Comment by tao12345666333** [comment]
Anything updated?  I will close this issue. And you can reopen it if necessary.

You can use Docker to try it.

```
sudo docker run -it -v $PWD:/src --rm taobeier/vim
```

Or use the GitLab registry, where the image is automatically built weekly and all dependent packages are updated.

```
sudo docker run -it -v $PWD:/src --rm registry.gitlab.com/taobeier/vim
```
