### ISSUE TITLE
现在提示升级vim

### ISSUE THREAD

**Issue by nameless1987** [tao12345666333/vim#29]
rpm -Uvh http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
rpm --import http://mirror.ghettoforge.org/distributions/gf/RPM-GPG-KEY-gf.el7
yum -y remove vim-minimal vim-common vim-enhanced sudo
yum -y --enablerepo=gf-plus install vim-enhanced sudo

**Comment by tao12345666333** [comment]
vim-go requires at least Vim 7.4.2009 or Neovim 0.3.1.

可以在配置文件中增加一行 `let g:go_version_warning = 0` 来关闭版本提醒
当然还是建议升级 Vim 以得到完整的特性支持。

**Comment by tao12345666333** [comment]
看起来没什么问题了。我先关闭了
