### ISSUE TITLE
When I run pymoderun, this problem is prompted?

### ISSUE THREAD

**Issue by tikboaHIT** [tao12345666333/vim#34]
![image](https://user-images.githubusercontent.com/39000220/130794550-bc851b2d-1522-4c11-956e-d86607450de2.png)

**Comment by tao12345666333** [comment]
![2023-06-02 13-03-45屏幕截图](https://github.com/tao12345666333/vim/assets/3264292/a8e49f63-4773-4cff-a869-fa406f939399)

Sorry for the long delay. I missed the notification message.


You can check if you have installed `python-mode` correctly by executing `:PymodeVersion`. You can refer to its documentation for installation. https://github.com/python-mode/python-mode

![2023-06-02 13-04-59屏幕截图](https://github.com/tao12345666333/vim/assets/3264292/b69a214e-ffb9-4fa9-a0a3-70bc86aa0864)

If you have any further questions, feel free to @ me anytime. Thanks!
