### ISSUE TITLE
在Mac下vim－airline显示有问题

### ISSUE THREAD

**Issue by cundi** [tao12345666333/vim#6]
看截图吧
![2016-04-05 10 58 04](https://cloud.githubusercontent.com/assets/10941075/14270107/56e0d188-fb1d-11e5-915d-d19298a51333.png)  

在另外一台Debian上也是有乱码，Google下说是airline_symbols的问题，找了几个方案试了下都不成功。

**Comment by tao12345666333** [comment]
你看一下 https://github.com/tao12345666333/vim/blob/master/vimrc#L474 这里的这几个符号在你电脑下显示的效果是什么?

**Comment by cundi** [comment]
@tao12345666333 这些分隔符vimrc显示都是方框里加问号如下截图  。现在用了其他字符替换，但是未能达到预期的效果😭

![2016-04-05 1 07 32](https://cloud.githubusercontent.com/assets/10941075/14271850/aebeadd2-fb2f-11e5-8ffc-8db0ad49fb61.png)

**Comment by tao12345666333** [comment]
@cundi 替换后, 你有没有到某个git 仓库中打开文件试试分支显示的效果?  我看你现在的截图, 基本效果已经有了的啊...模式, 位置之类的已经按照你替换后的字符显示了的~  你预期中还没达到的效果是什么?

**Comment by tao12345666333** [comment]
@cundi 这个问题我有了更好的解决方案， 我在Mac下使用vim 7.4 测试过了，可行。 

* clone [powerline fonts](https://github.com/powerline/fonts) 仓库
* 执行项目中的 `install.sh` 安装字体
* 修改终端配置中使用的字体为 xxx for Powerline即可。

祝好运～

**Comment by cundi** [comment]
@tao12345666333 好的。我试试看。😊

**Comment by cundi** [comment]
@tao12345666333 
截图报喜🌹😊。
从图上来看，都好了。
要谢谢你，还把个issue一直挂念着。

![2016-06-16 4 35 18](https://cloud.githubusercontent.com/assets/10941075/16110560/f51d43c6-33e0-11e6-89fe-7e69dcfa49c4.png)

**Comment by tao12345666333** [comment]
@cundi  恭喜!  不客气啦~ 能解决问题就好

**Comment by gradyjiang** [comment]
@tao12345666333  我也出现了这样的问题，
for power line 的字体也设置的，还是不行
<img width="1014" alt="a1daefc5-6dce-49a6-a7e9-eee418f37483" src="https://user-images.githubusercontent.com/30748169/29123558-b9d20a2e-7d48-11e7-869f-ae1347dc606d.png">
jian tou箭头始终显示不好，求帮助

**Comment by tao12345666333** [comment]
@gradyjiang  看你上面显示的部分，  你的字体， 没有安装好吧。

clone powerline fonts 仓库
执行项目中的 install.sh 安装字体
修改终端配置中使用的字体为 xxx for Powerline即可。

你有安装我说的这个步骤进行操作吗？  终端的配置需要修改的

**Comment by kmyuan2006** [comment]
你好，我现在也是配置这个airline_power,安装字体以后，有些还是显示不出来，请问这个还是字体的问题吗?我用的字体是DejaVu Sans Mono for Powerline
![selection_002](https://user-images.githubusercontent.com/5608841/46526128-fafd1980-c8bf-11e8-9f5b-e131e54da999.jpg)

**Comment by tao12345666333** [comment]
@kmyuan2006  是的，还是你的字体的问题。参考我上面说的步骤安装下字体 https://github.com/tao12345666333/vim/issues/6#issuecomment-321265918  记得修改终端的字体配置 以及确认字体是否已经成功安装。

**Comment by kmyuan2006** [comment]
你好，我安装了这些字体，然后也在Xresources中配置终端使用的字体了，他还是同样的显示，这个是跟系统有关系吗？
![selection_004](https://user-images.githubusercontent.com/5608841/46594727-6b49ac00-cb07-11e8-8b14-5b77ce4980d2.jpg)
![selection_003](https://user-images.githubusercontent.com/5608841/46594728-6b49ac00-cb07-11e8-8fbd-6d414f7313c0.jpg)

**Comment by tao12345666333** [comment]
@kmyuan2006  你使用现在的 Vim 打开 `vimrc` 文件的 498L ~ 512L https://github.com/tao12345666333/vim/blob/master/vimrc#L498-L512 看下是否能正常显示。

**Comment by kmyuan2006** [comment]
能打开的，终端字体应该是配置的，终端里面我配置了poweline试了下，是可以正常使用，只是VIM里面出问题了，
![selection_005](https://user-images.githubusercontent.com/5608841/46599108-ef585f80-cb18-11e8-8967-c5ccc5f17a61.jpg)

**Comment by tao12345666333** [comment]
@kmyuan2006  我指的是， 你打开那个文件查看下  vimrc 中那部分的显示是否正常。  如果正常 那就只是你终端配置的问题了， 如果不正常  就调整下 vimrc 中的配置。

**Comment by kmyuan2006** [comment]
哦，忘记反馈了，是正常的，而且我安装了gvim试了下，在gvim下显示是正常的

**Comment by kmyuan2006** [comment]
@tao12345666333 哦，忘记反馈了，是正常的，而且我安装了gvim试了下，在gvim下显示是正常的

**Comment by hao-lee** [comment]
> @cundi 这个问题我有了更好的解决方案， 我在Mac下使用vim 7.4 测试过了，可行。
> 
> * clone [powerline fonts](https://github.com/powerline/fonts) 仓库
> * 执行项目中的 `install.sh` 安装字体
> * 修改终端配置中使用的字体为 xxx for Powerline即可。
> 
> 祝好运～

叼，试了很多方案都不行，包括powerline官方教程里的用pip3安装，最后还是直接clone执行脚本来的简单粗暴。

**Comment by tao12345666333** [comment]
@hao-lee Thanks for feedback 😃
