### ISSUE TITLE
怎么 跳转到下一个语法错误提示？

### ISSUE THREAD

**Issue by lishiyong063** [tao12345666333/vim#9]
我用你的vim 配置，写python 的 时候 使用flake8 进行语法检查， 会有一些错误提示，但是不知道，是否有什么快捷键 [可以直接跳转到下一个错误。 相关插件:syntastic

**Comment by tao12345666333** [comment]
可以输入command  `:Errors` 查看错误列表， 选中想要查看的错误， 按回车进行跳转。 我考虑下是不是要加个快捷键好了~   感谢反馈~

**Comment by lishiyong063** [comment]
你已经加了快捷键了 \e  就是列出错误列表，但是我想的是 可以直接跳到下一条错误,，我看syntastic的文档它给出了一个coommand :lnext， 可以跳到下一个列表。 
但是我在python使用这个提示的是：No Errors 。 其实是有语法错误的。

**Comment by tao12345666333** [comment]
添加了新的快捷键在按了 `\e` 出现error 列表之后， 使用 `\p` 和 `\n` 进行前后跳转~

**Comment by lishiyong063** [comment]
好的，谢谢， 另外最后一个问题， 我主题换成了desert， 超过80列后 出现在vim中的竖线 很难看，我要怎么去解决它的样式，或者能否提示我一个关键的词， 我自己去搜索一下解决。

**Comment by tao12345666333** [comment]
直接执行

`:highlight ColorColumn ctermbg=blue guibg=blue`

这样就可以修改了。

**Comment by lishiyong063** [comment]
好的 非常感谢
